### ISSUE TITLE
Error while removing permissionset to User

### ISSUE THREAD

**Issue by harshal-suryawanshi-sp** [salesforceidentity/scimv2-pilot#17]
In User response JSON we are able to see entitlement assigned
"entitlements": [
    {
      "value": "00e36000000khvrAAA",
      "$ref": "/Entitlements/00e36000000khvrAAA",
      "display": "Chatter Free User",
      "type": "Profile",
      "primary": true
    },
    {
      "value": "0PS36000001S0STGA0",
      "$ref": "/Entitlements/0PS36000001S0STGA0",
      "display": "PermSet8",
      "type": "Permission Set",
      "primary": false
    }
  ],
But while removing permission set below is error 
{"errorCode":"APEX_ERROR","message":"System.NullPointerException: Attempt to de-reference a null object\n\nClass.UserResource.doPatch: line 1754, column 1"}

JSON PATCH : {"schemas":["urn:ietf:params:scim:api:messages:2.0:PatchOp"],"Operations":[{"op":"remove","path":"entitlements[value eq \"0PS36000001S0STGA0\"]"}]}

**Comment by iglazer** [comment]
We do not support filters in "path"

**Comment by ikram-momin-sp** [comment]
Ian, then what should the format of PATCH request for removing entitlement?

**Comment by iglazer** [comment]
This is PATCHing the User object? If so then just specify the value of the entitlement in the values section of the PATCH payload
