### ISSUE TITLE
members is not multivalued in Schemas/Group

### ISSUE THREAD

**Issue by chris-annino-sp** [salesforceidentity/scimv2-pilot#2]
querying /scim/v2/Schemas/urn:ietf:params:scim:schemas:core:2.0:Group returns a members attribute that says it's not multivalued when it actually is.

**Comment by chris-annino-sp** [comment]
Same thing for the addresses attribute in the User schema

**Comment by iglazer** [comment]
Members has been updated

**Comment by iglazer** [comment]
Addresses update - but be warned - although the spec says Addresses is a multi - Salesforce only supports a single address - trying to add more will fail (albeit gracefully)
