### ISSUE TITLE
Error while fetching extended attribute organization 

### ISSUE THREAD

**Issue by harshal-suryawanshi-sp** [salesforceidentity/scimv2-pilot#4]
https://scimv2-interop-dev-ed.my.salesforce.com/services/apexrest/scim/v2/Users?startIndex=1&count=100&attributes=urn:ietf:params:scim:schemas:extension:enterprise:2.0:User:organization
We are getting below error -
{
  "schemas": "[\"urn:ietf:params:scim:api:messages:2.0:Error\"]",
  "detail": "unexpected token: 'from'",
  "status": 400
}
This only for organization , rest other extended attributes we are able to fetch .

**Comment by iglazer** [comment]
Should be good now
