### ISSUE TITLE
Getting an exception while removing user from a group

### ISSUE THREAD

**Issue by nilmani-ghimire-sp** [salesforceidentity/scimv2-pilot#5]
Request being sent via POSTMAN:
PATCH /services/apexrest/scim/v2/Groups/00G36000001fOZmEAM HTTP/1.1
Host: scimv2-interop-dev-ed.my.salesforce.com
Authorization: Bearer XXXXX
Accept: application/scim+json
Content-Type: application/json
Cache-Control: no-cache
Postman-Token: 0055905f-d1ac-3af4-9da2-9362f6f6245f

  {
     "schemas":
      ["urn:ietf:params:scim:api:messages:2.0:PatchOp"],
     "Operations":[{
       "op":"remove",
       "path":"members[value eq \"00536000002ocEcAAI\"]"
     }]
   }

Exception Message:
{
  "schemas": "[\"urn:ietf:params:scim:api:messages:2.0:Error\"]",
  "detail": "Attempt to de-reference a null object FIELD_INTEGRITY_EXCEPTIONs likely caused by attempted assignment to wrong User license.",
  "status": 500
}

**Comment by iglazer** [comment]
We do not support filter conditions on path. Use the following instead:
{
	"schemas": [
		"urn:ietf:params:scim:api:messages:2.0:PatchOp"
	],
	"Operations": [{
		"op": "remove",
		"path": "members",
		"value": [{
			"value": "00536000002ocEcAAI"
		}]
	}]
}

**Comment by iglazer** [comment]
Added better error handing
