### ISSUE TITLE
Unsupported attribute: profileUrl while fetching resource 

### ISSUE THREAD

**Issue by harshal-suryawanshi-sp** [salesforceidentity/scimv2-pilot#6]
we are trying to get users with attribute profileUrl /Users?attributes=profileUrl
getting below exception:
{ "errorCode" : "APEX_ERROR", "message" : "System.LimitException: Too many SOQL queries: 101\n\nClass.UserResource.serializeUserWithGenerator: line 1214, column 1\nClass.UsersResource.serializeUsers: line 27, column 1\nClass.UsersResource.doGet: line 78, column 1" }

And if we see in schema profileUrl is not mentioned as returned=never   
 {
      "name": "profileUrl",
      "type": "string",
      "multiValued": false,
      "description": "URL to a page representing the User online",
      "mutability": "readWrite",
      "required": false,
      "caseExact": false
    },

**Comment by iglazer** [comment]
Fixed
